### ISSUE TITLE
Resolve flaky tests

### ISSUE THREAD

**Issue by Cruikshanks** [DEFRA/water-abstraction-team#128]
Since we completed Issue #124 we have noticed some flakiness in our tests.

We suspect it results from older tests written, assuming that the DB would always be clean before a test ran. Now, that is no longer the case, so they intermittently fail.

We want to stomp this out. This this ticket covers any work we do towards that goal. You are also encouraged to log an fails here you are sure are nothing to do with what you were working on, see we can see if there are any 'hot spots' we should be tackling first

---

**Comment by Cruikshanks** [comment]
Got a few locally

```
1267) Fetch Charge Versions service when there are charge versions that should be considered for the next supplementary billing returns both "current" and "superseded" SROC charge version that are applicable:

Expected [..] to have a length of 4 but got 5

at /home/repos/water-abstraction-system/test/services/bill-runs/supplementary/fetch-charge-versions.service.test.js:306:45
```

```
1271) Fetch Charge Versions service when there are charge versions that should be considered for the next supplementary billing including those linked to soft-deleted workflow records returns the SROC charge versions that are applicable:

Expected [..] to have a length of 4 but got 5

at /home/repos/water-abstraction-system/test/services/bill-runs/supplementary/fetch-charge-versions.service.test.js:283:47
```

```
1272) Fetch Charge Versions service when there are charge versions that should be considered for the next supplementary billing including those linked to soft-deleted workflow records returns a unique list of licenceIds from SROC charge versions that are applicable:

Expected [..] to have a length of 1 but got 2

at /home/repos/water-abstraction-system/test/services/bill-runs/supplementary/fetch-charge-versions.service.test.js:298:52
```

**Comment by StuAA78** [comment]
We have a situation where for some reason several tests failed in CI, but running the tests locally with the same seed to ensure they run in the same order results in only one, entirely different, test failing!

In CI:

```
  2240) Supplementary Process billing period service when the service is called and there are charge versions to process but none of them are billable because the billable days calculated as 0 and there are no previous billed transactions returns false (bill run is empty):

      Cannot destructure property 'id' of 'bills[chargeVersion.billingAccountId]' as it is undefined.

      at /home/runner/work/water-abstraction-system/water-abstraction-system/app/services/bill-runs/supplementary/pre-generate-billing-data.service.js:70:205
      at Array.reduce (<anonymous>)
      at _preGenerateBillLicences (/home/runner/work/water-abstraction-system/water-abstraction-system/app/services/bill-runs/supplementary/pre-generate-billing-data.service.js:69:216)
      at Object.go (/home/runner/work/water-abstraction-system/water-abstraction-system/app/services/bill-runs/supplementary/pre-generate-billing-data.service.js:27:196)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async Object.go (/home/runner/work/water-abstraction-system/water-abstraction-system/app/services/bill-runs/supplementary/process-billing-period.service.js:34:197)
      at async /home/runner/work/water-abstraction-system/water-abstraction-system/test/services/bill-runs/supplementary/process-billing-period.service.test.js:108:30
      at async Immediate.<anonymous> (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/@hapi/lab/lib/runner.js:659:21)

  2241) Supplementary Process billing period service when the service is called and there are charge versions to process but none of them are billable because the charge version status is "superseded" and there are no previously billed transactions returns false (bill run is empty):

      Cannot destructure property 'id' of 'bills[chargeVersion.billingAccountId]' as it is undefined.

      at /home/runner/work/water-abstraction-system/water-abstraction-system/app/services/bill-runs/supplementary/pre-generate-billing-data.service.js:70:205
      at Array.reduce (<anonymous>)
      at _preGenerateBillLicences (/home/runner/work/water-abstraction-system/water-abstraction-system/app/services/bill-runs/supplementary/pre-generate-billing-data.service.js:69:216)
      at Object.go (/home/runner/work/water-abstraction-system/water-abstraction-system/app/services/bill-runs/supplementary/pre-generate-billing-data.service.js:27:196)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async Object.go (/home/runner/work/water-abstraction-system/water-abstraction-system/app/services/bill-runs/supplementary/process-billing-period.service.js:34:197)
      at async /home/runner/work/water-abstraction-system/water-abstraction-system/test/services/bill-runs/supplementary/process-billing-period.service.test.js:144:30
      at async Immediate.<anonymous> (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/@hapi/lab/lib/runner.js:659:21)

  2242) Supplementary Process billing period service when the service is called and there are charge versions to process and they are billable returns true (bill run is not empty):

      Cannot destructure property 'id' of 'bills[chargeVersion.billingAccountId]' as it is undefined.

      at /home/runner/work/water-abstraction-system/water-abstraction-system/app/services/bill-runs/supplementary/pre-generate-billing-data.service.js:70:205
      at Array.reduce (<anonymous>)
      at _preGenerateBillLicences (/home/runner/work/water-abstraction-system/water-abstraction-system/app/services/bill-runs/supplementary/pre-generate-billing-data.service.js:69:216)
      at Object.go (/home/runner/work/water-abstraction-system/water-abstraction-system/app/services/bill-runs/supplementary/pre-generate-billing-data.service.js:27:196)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async Object.go (/home/runner/work/water-abstraction-system/water-abstraction-system/app/services/bill-runs/supplementary/process-billing-period.service.js:34:197)
      at async /home/runner/work/water-abstraction-system/water-abstraction-system/test/services/bill-runs/supplementary/process-billing-period.service.test.js:225:26
      at async Immediate.<anonymous> (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/@hapi/lab/lib/runner.js:659:21)

  2243) Supplementary Process billing period service when the service errors because generating the calculated transactions fails throws a BillRunError with the correct code:

      Expected [TypeError: Cannot destructure property 'id' of 'bills[chargeVersion.billingAccountId]' as it is undefined.] to be an instance of BillRunError

      at /home/runner/work/water-abstraction-system/water-abstraction-system/test/services/bill-runs/supplementary/process-billing-period.service.test.js:260:32

  2244) Supplementary Process billing period service when the service errors because sending the transactions fails throws a BillRunError with the correct code:

      Expected [TypeError: Cannot destructure property 'id' of 'bills[chargeVersion.billingAccountId]' as it is undefined.] to be an instance of BillRunError

      at /home/runner/work/water-abstraction-system/water-abstraction-system/test/services/bill-runs/supplementary/process-billing-period.service.test.js:275:32
```

Locally:

```
  1649) Fetch Licence Contact Details service when the licence has a licence document header returns the matching licence and licence document header:

      Expected {
        id: 'fea88a95-d81f-4c5c-b497-00e5891a5861',
        licenceRef: '01/123',
        licenceDocumentHeader: {
          id: 'e27682b4-8c28-4db0-bb0a-685380537bc5',
          metadata: {
            // ...
          }
        }
      } to equal specified value: {
        id: '9b883186-9bf2-4de8-b790-6cfd71b646e5',
        licenceRef: '01/35/83/6135',
        licenceDocumentHeader: {
          id: 'd659fae6-baf4-4c57-a836-e1f19b25b07f',
          metadata: {
            // ...
          }
        }
      }


      at /home/repos/water-abstraction-system/test/services/licences/fetch-licence-contact-details.service.test.js:38:25
```

```
Randomized with seed: 247. Use --shuffle --seed 247 to run tests in same order again.
```

**Comment by StuAA78** [comment]
```
  2897) Fetch Charge Versions service when there are no charge version that should be considered for the next supplementary billing because they all have start dates after the billing period returns no applicable licenceIds or charge versions:

      Expected [
  ChargeVersionModel {
    ...
  }
] to be empty

      at /home/runner/work/water-abstraction-system/water-abstraction-system/test/services/bill-runs/supplementary/fetch-charge-versions.service.test.js:64:45

  2898) Fetch Charge Versions service when there are no charge version that should be considered for the next supplementary billing because the licences flagged for supplementary billing are linked to a different region returns no applicable licenceIds or charge versions:

      Expected [
  ChargeVersionModel {
    ...
  }
] to be empty

      at /home/runner/work/water-abstraction-system/water-abstraction-system/test/services/bill-runs/supplementary/fetch-charge-versions.service.test.js:83:45

  2899) Fetch Charge Versions service when there are no charge version that should be considered for the next supplementary billing because they are all linked to licences in workflow returns no applicable licenceIds or charge versions:

      Expected [
  ChargeVersionModel {
    ...
  }
] to be empty

      at /home/runner/work/water-abstraction-system/water-abstraction-system/test/services/bill-runs/supplementary/fetch-charge-versions.service.test.js:100:45

  2900) Fetch Charge Versions service when there are no charge version that should be considered for the next supplementary billing because none of them are linked to a licence flagged "includeInSrocBilling" returns no applicable licenceIds or charge versions:

      Expected [
  ChargeVersionModel {
    ...
  }
] to be empty

      at /home/runner/work/water-abstraction-system/water-abstraction-system/test/services/bill-runs/supplementary/fetch-charge-versions.service.test.js:114:45

  2901) Fetch Charge Versions service when there are no charge version that should be considered for the next supplementary billing because all the applicable charge versions have a "draft" status returns no applicable licenceIds or charge versions:

      Expected [
  ChargeVersionModel {
    ...
  }
] to be empty

      at /home/runner/work/water-abstraction-system/water-abstraction-system/test/services/bill-runs/supplementary/fetch-charge-versions.service.test.js:129:45

  2902) Fetch Charge Versions service when there are no charge version that should be considered for the next supplementary billing because all of them are for the "alcs" (presroc) scheme returns no applicable licenceIds or charge versions:

      Expected [
  ChargeVersionModel {
    ...
  }
] to be empty

      at /home/runner/work/water-abstraction-system/water-abstraction-system/test/services/bill-runs/supplementary/fetch-charge-versions.service.test.js:145:45

  2903) Fetch Charge Versions service when there are no charge version that should be considered for the next supplementary billing because none of them have a "billingAccountId" returns the licenceId but no applicable charge versions:

      Expected [
  ChargeVersionModel {
    ...
  }
] to be empty

      at /home/runner/work/water-abstraction-system/water-abstraction-system/test/services/bill-runs/supplementary/fetch-charge-versions.service.test.js:161:45


7 of 3558 tests failed (1 skipped)
Test duration: 32241 ms
Leaks: No issues
Randomized with seed: 111. Use --shuffle --seed 111 to run tests in same order again.
```

**Comment by StuAA78** [comment]
In CI:

```
  1029) Licences - End Dates - Process Licence End Date Changes service when processing the licence end date changes processes the changed licence for supplementary billing flags:

      Attempted to wrap go which is already wrapped

      at checkWrappedMethod (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/util/core/wrap-method.js:67:21)
      at wrapMethod (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/util/core/wrap-method.js:132:13)
      at Function.stub (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/stub.js:130:44)
      at Sandbox.stub (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/sandbox.js:389:39)
      at /home/runner/work/water-abstraction-system/water-abstraction-system/test/services/licences/end-dates/process-licence-end-date-changes.service.test.js:47:37
      at Immediate._onImmediate (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/@hapi/lab/lib/runner.js:659:35)
      at process.processImmediate (node:internal/timers:491:21)
  --------------
  Error: Stack Trace for original
      at extendObjectWithWrappedMethods (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/util/core/wrap-method.js:173:34)
      at wrapMethod (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/util/core/wrap-method.js:161:5)
      at Function.stub (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/stub.js:130:44)
      at Sandbox.stub (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/sandbox.js:389:39)
      at /home/runner/work/water-abstraction-system/water-abstraction-system/test/services/return-versions/setup/check/submit-check.service.test.js:109:15
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async Immediate.<anonymous> (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/@hapi/lab/lib/runner.js:659:21)

  1030) Licences - End Dates - Process Licence End Date Changes service when processing the licence end date changes and the app is now managing "requirements for returns" processes the changed licence for reissuing return logs:

      Attempted to wrap go which is already wrapped

      at checkWrappedMethod (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/util/core/wrap-method.js:67:21)
      at wrapMethod (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/util/core/wrap-method.js:132:13)
      at Function.stub (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/stub.js:130:44)
      at Sandbox.stub (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/sandbox.js:389:39)
      at /home/runner/work/water-abstraction-system/water-abstraction-system/test/services/licences/end-dates/process-licence-end-date-changes.service.test.js:46:39
      at Immediate._onImmediate (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/@hapi/lab/lib/runner.js:659:35)
      at process.processImmediate (node:internal/timers:491:21)
  --------------
  Error: Stack Trace for original
      at extendObjectWithWrappedMethods (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/util/core/wrap-method.js:173:34)
      at wrapMethod (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/util/core/wrap-method.js:161:5)
      at Function.stub (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/stub.js:130:44)
      at Sandbox.stub (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/sandbox.js:389:39)
      at /home/runner/work/water-abstraction-system/water-abstraction-system/test/services/licences/end-dates/process-licence-end-date-changes.service.test.js:46:39
      at Immediate.<anonymous> (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/@hapi/lab/lib/runner.js:659:35)
      at process.processImmediate (node:internal/timers:491:21)

  1031) Licences - End Dates - Process Licence End Date Changes service when processing the licence end date changes and the app is not yet managing "requirements for returns" does not process the changed licence for reissuing return logs:

      Attempted to wrap go which is already wrapped

      at checkWrappedMethod (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/util/core/wrap-method.js:67:21)
      at wrapMethod (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/util/core/wrap-method.js:132:13)
      at Function.stub (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/stub.js:130:44)
      at Sandbox.stub (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/sandbox.js:389:39)
      at /home/runner/work/water-abstraction-system/water-abstraction-system/test/services/licences/end-dates/process-licence-end-date-changes.service.test.js:46:39
      at Immediate._onImmediate (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/@hapi/lab/lib/runner.js:659:35)
      at process.processImmediate (node:internal/timers:491:21)
  --------------
  Error: Stack Trace for original
      at extendObjectWithWrappedMethods (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/util/core/wrap-method.js:173:34)
      at wrapMethod (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/util/core/wrap-method.js:161:5)
      at Function.stub (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/stub.js:130:44)
      at Sandbox.stub (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/sandbox.js:389:39)
      at /home/runner/work/water-abstraction-system/water-abstraction-system/test/services/licences/end-dates/process-licence-end-date-changes.service.test.js:46:39
      at Immediate.<anonymous> (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/@hapi/lab/lib/runner.js:659:35)
      at process.processImmediate (node:internal/timers:491:21)

  1032) Licences - End Dates - Process Licence End Date Changes service when processing the licence end date changes and when the processing is complete deletes the licence end date change record:

      Attempted to wrap go which is already wrapped

      at checkWrappedMethod (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/util/core/wrap-method.js:67:21)
      at wrapMethod (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/util/core/wrap-method.js:132:13)
      at Function.stub (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/stub.js:130:44)
      at Sandbox.stub (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/sandbox.js:389:39)
      at /home/runner/work/water-abstraction-system/water-abstraction-system/test/services/licences/end-dates/process-licence-end-date-changes.service.test.js:46:39
      at Immediate._onImmediate (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/@hapi/lab/lib/runner.js:659:35)
      at process.processImmediate (node:internal/timers:491:21)
  --------------
  Error: Stack Trace for original
      at extendObjectWithWrappedMethods (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/util/core/wrap-method.js:173:34)
      at wrapMethod (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/util/core/wrap-method.js:161:5)
      at Function.stub (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/stub.js:130:44)
      at Sandbox.stub (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/sandbox.js:389:39)
      at /home/runner/work/water-abstraction-system/water-abstraction-system/test/services/licences/end-dates/process-licence-end-date-changes.service.test.js:46:39
      at Immediate.<anonymous> (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/@hapi/lab/lib/runner.js:659:35)
      at process.processImmediate (node:internal/timers:491:21)

  1033) Licences - End Dates - Process Licence End Date Changes service when processing the licence end date changes and when the processing is complete logs the completed licence change:

      Attempted to wrap go which is already wrapped

      at checkWrappedMethod (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/util/core/wrap-method.js:67:21)
      at wrapMethod (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/util/core/wrap-method.js:132:13)
      at Function.stub (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/stub.js:130:44)
      at Sandbox.stub (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/sandbox.js:389:39)
      at /home/runner/work/water-abstraction-system/water-abstraction-system/test/services/licences/end-dates/process-licence-end-date-changes.service.test.js:46:39
      at Immediate._onImmediate (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/@hapi/lab/lib/runner.js:659:35)
      at process.processImmediate (node:internal/timers:491:21)
  --------------
  Error: Stack Trace for original
      at extendObjectWithWrappedMethods (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/util/core/wrap-method.js:173:34)
      at wrapMethod (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/util/core/wrap-method.js:161:5)
      at Function.stub (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/stub.js:130:44)
      at Sandbox.stub (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/sandbox.js:389:39)
      at /home/runner/work/water-abstraction-system/water-abstraction-system/test/services/licences/end-dates/process-licence-end-date-changes.service.test.js:46:39
      at Immediate.<anonymous> (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/@hapi/lab/lib/runner.js:659:35)
      at process.processImmediate (node:internal/timers:491:21)

  1034) Licences - End Dates - Process Licence End Date Changes service when processing the licence end date changes and when the processing is complete logs the time taken in milliseconds and seconds:

      Attempted to wrap go which is already wrapped

      at checkWrappedMethod (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/util/core/wrap-method.js:67:21)
      at wrapMethod (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/util/core/wrap-method.js:132:13)
      at Function.stub (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/stub.js:130:44)
      at Sandbox.stub (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/sandbox.js:389:39)
      at /home/runner/work/water-abstraction-system/water-abstraction-system/test/services/licences/end-dates/process-licence-end-date-changes.service.test.js:46:39
      at Immediate._onImmediate (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/@hapi/lab/lib/runner.js:659:35)
      at process.processImmediate (node:internal/timers:491:21)
  --------------
  Error: Stack Trace for original
      at extendObjectWithWrappedMethods (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/util/core/wrap-method.js:173:34)
      at wrapMethod (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/util/core/wrap-method.js:161:5)
      at Function.stub (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/stub.js:130:44)
      at Sandbox.stub (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/sandbox.js:389:39)
      at /home/runner/work/water-abstraction-system/water-abstraction-system/test/services/licences/end-dates/process-licence-end-date-changes.service.test.js:46:39
      at Immediate.<anonymous> (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/@hapi/lab/lib/runner.js:659:35)
      at process.processImmediate (node:internal/timers:491:21)

  1035) Licences - End Dates - Process Licence End Date Changes service when there is an error during the processing of a licence handles the error:

      Attempted to wrap go which is already wrapped

      at checkWrappedMethod (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/util/core/wrap-method.js:67:21)
      at wrapMethod (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/util/core/wrap-method.js:132:13)
      at Function.stub (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/stub.js:130:44)
      at Sandbox.stub (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/sandbox.js:389:39)
      at /home/runner/work/water-abstraction-system/water-abstraction-system/test/services/licences/end-dates/process-licence-end-date-changes.service.test.js:121:41
      at Immediate._onImmediate (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/@hapi/lab/lib/runner.js:659:35)
      at process.processImmediate (node:internal/timers:491:21)
  --------------
  Error: Stack Trace for original
      at extendObjectWithWrappedMethods (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/util/core/wrap-method.js:173:34)
      at wrapMethod (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/util/core/wrap-method.js:161:5)
      at Function.stub (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/stub.js:130:44)
      at Sandbox.stub (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/sinon/lib/sinon/sandbox.js:389:39)
      at /home/runner/work/water-abstraction-system/water-abstraction-system/test/services/licences/end-dates/process-licence-end-date-changes.service.test.js:46:39
      at Immediate.<anonymous> (/home/runner/work/water-abstraction-system/water-abstraction-system/node_modules/@hapi/lab/lib/runner.js:659:35)
      at process.processImmediate (node:internal/timers:491:21)
```
```
Randomized with seed: 111. Use --shuffle --seed 111 to run tests in same order again.
```
