### ISSUE TITLE
Service unit tests rely on real Notify API service

### ISSUE THREAD

**Issue by Cruikshanks** [DEFRA/water-abstraction-team#35]
Found when working on [Apply consistent CI workflow](https://github.com/DEFRA/water-abstraction-service/pull/1710). If we don't provide valid Notify API keys then the tests fail with `403 Unauthorized` returned.

We found this out by replacing `TEST_NOTIFY_KEY` and `WHITELIST_NOTIFY_KEY` with fake values and then running the tests in CI.

All calls to Notify _should_ be stubbed out 😩 

```
3) Test sending a email notification The API should throw an error when a template id that is missing in notify is supplied:
      actual expected
      403400
      Expected 403 to equal specified value: 400
      at /home/runner/work/water-abstraction-service/water-abstraction-service/test/controllers/notify.test.js:81:31
  5) Test sending a email notification The API should not throw an error when valid email address specified for message of type email:
      actual expected
      403200
      Expected 403 to equal specified value: 200
      at /home/runner/work/water-abstraction-service/water-abstraction-service/test/controllers/notify.test.js:120:31
  6) Test sending a SMS notification The API should not throw an error when valid number specified for message of type sms:
      actual expected
      403200
      Expected 403 to equal specified value: 200
      at /home/runner/work/water-abstraction-service/water-abstraction-service/test/controllers/notify.test.js:141:31
  7) Test sending a Postal notification The API should not throw an error when valid address specified for message of type letter:
      actual expected
      403200
      Expected 403 to equal specified value: 200
      at /home/runner/work/water-abstraction-service/water-abstraction-service/test/controllers/notify.test.js:168:31
  8) Scheduled notifications The API should not throw an error when scheduling a message:
      actual expected
      403200
      Expected 403 to equal specified value: 200
      at /home/runner/work/water-abstraction-service/water-abstraction-service/test/controllers/notify.test.js:194:31
  5235) Test notify module Enqueue message for immediate send:
      403 - {"errors":[{"error":"AuthError","message":"Invalid token: service not found"}],"status_code":403}
      at new StatusCodeError (/home/runner/work/water-abstraction-service/water-abstraction-service/node_modules/request-promise-core/lib/errors.js:32:15)
      at Request.plumbing.callback (/home/runner/work/water-abstraction-service/water-abstraction-service/node_modules/request-promise-core/lib/plumbing.js:104:33)
      at Request.RP$callback [as _callback] (/home/runner/work/water-abstraction-service/water-abstraction-service/node_modules/request-promise-core/lib/plumbing.js:46:31)
      at Request.self.callback (/home/runner/work/water-abstraction-service/water-abstraction-service/node_modules/request/request.js:185:22)
      at Request.emit (events.js:400:28)
      at Request.emit (domain.js:475:12)
      at Request.<anonymous> (/home/runner/work/water-abstraction-service/water-abstraction-service/node_modules/request/request.js:1154:10)
      at Request.emit (events.js:400:28)
      at Request.emit (domain.js:475:12)
      at IncomingMessage.<anonymous> (/home/runner/work/water-abstraction-service/water-abstraction-service/node_modules/request/request.js:1076:12)
      at Object.onceWrapper (events.js:519:28)
      at IncomingMessage.emit (events.js:412:35)
      at IncomingMessage.emit (domain.js:475:12)
      at endReadableNT (internal/streams/readable.js:1334:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21)
6 of 5758 tests failed
```

**Comment by Cruikshanks** [comment]
Just found another issue this causes. When depdendabot raises a PR it is not permitted to access repo secrets. This is why the SonarCloud Analysis step is skipped in our CI workflow (`SONAR_TOKEN` is out of bounds).

Unfortunately, the same applies to other secret tokens such as those we're using to store the real Notify API keys 😡 😩 .

Till we sport out this issue all Dependabot PRs for the service will fail the build.

**Comment by StuAA78** [comment]
[While investigating this ](https://github.com/DEFRA/water-abstraction-service/pull/1736)we realised that the failing unit tests maybe aren't useful ones. They are testing the functionality of Notify itself (eg. "If we send a request without xyz details, does Notify return an error?"). So, we believe that we can either delete the tests completely, or rewrite them to be more useful (eg. "If Notify returns an error, do we handle it correctly?")
