### ISSUE TITLE
Stop spamming logs on unhandled exception

### ISSUE THREAD

**Issue by Cruikshanks** [DEFRA/water-abstraction-team#42]
One of the things that drives us nuts is when an unhandled rejection or uncaught exception is thrown the log is updated with _thousands_ (and we really mean it!) of lines of error output.

This mostly happens when making HTTP calls between the services because there doesn't seem to have been a conscious plan to cater for errors. So, we think it's pretty much the entirety of the `request` package being spat out!

Thankfully the error is shown at the bottom, but it makes trying to see what happens before the error impossible, especially when looking at **production** logs in AWS CloudWatch.

We've tracked it down to what seems to be a standard pattern in all of the root `index.js` files.

```javascript
const processError = message => err => {
  logger.error(message, err) // <- HERE!
  process.exit(1)
}

process
  .on('unhandledRejection', processError('unhandledRejection'))
  .on('uncaughtException', processError('uncaughtException'))
  .on('SIGINT', async () => {
    logger.info('Stopping water service')
```

Passsing the error instance to the logger (which is [winston](https://github.com/winstonjs/winston) underneath) is what causes the spamming. In testing if we do the following

```javascript
const processError = message => err => {
  logger.error(message, err.stack)
  process.exit(1)
}
```

We get the following output (as an example)

```text
2022-08-10T21:56:11.956Z - error: StatusCodeError: 404 - {"statusCode":404,"error":"Not Found","message":"Not Found"}
    at new StatusCodeError (/vagrant/water-abstraction-service/node_modules/request-promise-native/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/vagrant/water-abstraction-service/node_modules/request-promise-native/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/vagrant/water-abstraction-service/node_modules/request-promise-native/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/vagrant/water-abstraction-service/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.emit (domain.js:475:12)
    at Request.<anonymous> (/vagrant/water-abstraction-service/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:400:28)
    at Request.emit (domain.js:475:12)
    at IncomingMessage.<anonymous> (/vagrant/water-abstraction-service/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

So, this issue covers going through the apps and making the change to `processError()`.

- [x] water-abstraction-import
- [x] water-abstraction-permit-repository
- [x] water-abstraction-reporting
- [x] water-abstraction-returns
- [x] water-abstraction-service
- [x] water-abstraction-tactical-crm
- [x] water-abstraction-tactical-idm
- [x] water-abstraction-ui

**Comment by Beckyrose200** [comment]
<img src="https://media4.giphy.com/media/l0IycQmt79g9XzOWQ/giphy.gif"/>
